apiVersion : apps/v1
kind: Deployment
metadata:
  name: fsmicro
  labels:
    app: fsharp-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      service: fsmicro
  template:
    metadata:
      labels:
        app: fsharp-microservice
        service: fsmicro
    spec:
      containers:
        - name: api
          image: devstacr.azurecr.io/fsapi:k8s
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fsmicro
  labels:
    app: fsharp-microservice
    service: fsmicro
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    service: fsmicro
